#!/bin/bash
# install-clean.sh - Instalación limpia garantizada

set -e

echo "🛡️ INSTALACIÓN LIMPIA DEL FORO"
echo "=============================="

# Auto-detectar configuración
PUBLIC_IP=$(curl -s https://ipinfo.io/ip 2>/dev/null || echo "localhost")
LOCAL_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")
HOSTNAME=$(hostname -f 2>/dev/null || hostname)

# Determinar mejor configuración
if [[ $HOSTNAME == *.* && $HOSTNAME != "localhost" ]]; then
    SERVER_HOST=$HOSTNAME
    FRONTEND_URL="https://$HOSTNAME"
    echo "✅ Detectado dominio: $HOSTNAME"
elif [[ $PUBLIC_IP != "localhost" ]]; then
    SERVER_HOST=$PUBLIC_IP
    FRONTEND_URL="http://$PUBLIC_IP:9050"
    echo "✅ Detectada IP pública: $PUBLIC_IP"
else
    SERVER_HOST=$LOCAL_IP
    FRONTEND_URL="http://$LOCAL_IP:9050"
    echo "✅ Usando IP local: $LOCAL_IP"
fi

# Crear .env automático
cat > .env << EOF
# ===== CONFIGURACIÓN AUTO-GENERADA =====
SERVER_IP=$SERVER_HOST
FRONTEND_PORT=9050

# ===== BASE DE DATOS =====
POSTGRES_USER=foro_user
POSTGRES_PASSWORD=SecurePass_$(date +%s)
POSTGRES_DB=forumDB

# ===== SEGURIDAD =====
JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || echo "AutoGenerated_$(date +%s)")
JWT_EXPIRES_IN=7d
EMAIL_VERIFICATION_SECRET=$(openssl rand -hex 24 2>/dev/null || echo "EmailSecret_$(date +%s)")
BCRYPT_ROUNDS=12

# ===== EMAIL =====
MAILER_SERVICE=gmail
MAILER_EMAIL=admin@localhost
MAILER_SECRET_KEY=dummy_password

# ===== CONFIGURACIÓN AVANZADA =====
ENABLE_QUERY_LOGGING=false
NODE_ENV=production
EOF

echo "✅ Archivo .env generado con configuración segura"

# Limpiar instalación anterior
echo "🧹 Limpiando instalación anterior..."
docker-compose down -v 2>/dev/null || true

# Desplegar
echo "🚀 Desplegando servicios..."
docker-compose up -d

# Verificar
echo "⏳ Esperando que los servicios estén listos..."
sleep 90

if docker-compose ps | grep -q "Up.*healthy"; then
    echo ""
    echo "🎉 ¡INSTALACIÓN COMPLETADA!"
    echo "========================="
    echo "🌐 Accede al foro en: $FRONTEND_URL"
    echo "👤 Usuarios disponibles:"
    echo "   Admin: admin@foro.local / admin123"
    echo "   Mod: mod@foro.local / admin123"
    echo "   User: user@foro.local / admin123"
    echo ""
    echo "🔧 Comandos útiles:"
    echo "   docker-compose ps          # Ver estado"
    echo "   docker-compose logs -f     # Ver logs en tiempo real"
    echo "   docker-compose logs backend # Ver logs del backend"
    echo ""
    echo "✅ PgBouncer configurado con fallback automático"
    echo "✅ Auto-detección de URLs activada"
else
    echo ""
    echo "⚠️ Algunos servicios pueden tardar más. Ver estado:"
    docker-compose ps
    echo ""
    echo "Ver logs: docker-compose logs -f"
fi